# Generated by Django 5.1.15 on 2026-04-10 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('execution_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('broker_execution_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('executed_at', models.DateTimeField()),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('liquidity', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'execution',
                'verbose_name_plural': 'executions',
                'db_table': 'oms_execution',
            },
        ),
        migrations.CreateModel(
            name='PnLSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('total_unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_positions', models.PositiveIntegerField(default=0)),
                ('long_positions', models.PositiveIntegerField(default=0)),
                ('short_positions', models.PositiveIntegerField(default=0)),
                ('total_market_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cost_basis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('positions_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'P&L snapshot',
                'verbose_name_plural': 'P&L snapshots',
                'db_table': 'oms_pnl_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'db_table': 'oms_position',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Stock'), ('OPTION', 'Option'), ('FUTURE', 'Future'), ('FOREX', 'Forex'), ('BOND', 'Bond'), ('ETF', 'ETF'), ('MUTUAL_FUND', 'Mutual Fund'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('exchange', models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('ARCA', 'NYSE Arca'), ('BATS', 'BATS Exchange'), ('EDGX', 'EDGX Exchange'), ('EDGA', 'EDGA Exchange'), ('IB_SMART', 'IB Smart Routing'), ('IB_CRYPTO', 'IB Crypto'), ('IB_FOREX', 'IB Forex'), ('IB_FUTURES', 'IB Futures'), ('CBOE', 'CBOE Options Exchange'), ('CME', 'CME Group'), ('ICE', 'Intercontinental Exchange'), ('LSE', 'London Stock Exchange'), ('TSE', 'Tokyo Stock Exchange'), ('OTHER', 'Other Exchange')], db_index=True, max_length=20)),
                ('contract_id', models.CharField(blank=True, max_length=100)),
                ('sec_type', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('min_tick_size', models.DecimalField(decimal_places=6, default=Decimal('0.01'), max_digits=10)),
                ('min_order_size', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=15)),
                ('max_order_size', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_tradable', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'instrument',
                'verbose_name_plural': 'instruments',
                'db_table': 'oms_instrument',
                'indexes': [models.Index(fields=['symbol'], name='oms_instrum_symbol_748845_idx'), models.Index(fields=['instrument_type'], name='oms_instrum_instrum_9a06b1_idx'), models.Index(fields=['exchange'], name='oms_instrum_exchang_d23185_idx'), models.Index(fields=['is_active'], name='oms_instrum_is_acti_c1d7eb_idx'), models.Index(fields=['is_tradable'], name='oms_instrum_is_trad_6711ee_idx'), models.Index(fields=['expiration_date'], name='oms_instrum_expirat_5e5582_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('broker_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop Limit'), ('TRAILING_STOP', 'Trailing Stop'), ('TRAILING_STOP_LIMIT', 'Trailing Stop Limit'), ('PEGGED', 'Pegged'), ('AUCTION', 'Auction'), ('VOLATILITY', 'Volatility'), ('ADAPTIVE', 'Adaptive')], db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('BUY_TO_COVER', 'Buy to Cover'), ('SELL_SHORT', 'Sell Short')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('trailing_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_in_force', models.CharField(choices=[('DAY', 'Day'), ('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate or Cancel'), ('FOK', 'Fill or Kill'), ('GTD', 'Good Till Date'), ('OPG', 'Opening'), ('CLS', 'Closing'), ('MOC', 'Market on Close'), ('LOC', 'Limit on Close')], default='DAY', max_length=20)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('PENDING_SUBMIT', 'Pending Submit'), ('SUBMITTED', 'Submitted'), ('PENDING_CANCEL', 'Pending Cancel'), ('CANCELLED', 'Cancelled'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('PENDING_REPLACE', 'Pending Replace'), ('REPLACED', 'Replaced'), ('ROUTED', 'Routed'), ('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('RISK_REJECTED', 'Risk Rejected'), ('COMPLIANCE_REJECTED', 'Compliance Rejected')], db_index=True, default='NEW', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('average_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reject_reason', models.TextField(blank=True)),
                ('reject_code', models.CharField(blank=True, max_length=50)),
                ('risk_check_passed', models.BooleanField(blank=True, null=True)),
                ('compliance_check_passed', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='brokers.brokeraccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='oms.instrument')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'oms_order',
            },
        ),
    ]
