# Generated by Django 5.1.15 on 2026-04-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('oms', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strategy_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='strategies.strategyrun'),
        ),
        migrations.AddField(
            model_name='execution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='oms.order'),
        ),
        migrations.AddField(
            model_name='pnlsnapshot',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_snapshots', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='position',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='position',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='oms.instrument'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_order_id'], name='oms_order_client__8ad41b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_order_id'], name='oms_order_broker__c5c806_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['state'], name='oms_order_state_bc5f55_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['submitted_at'], name='oms_order_submitt_206d39_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_account', 'submitted_at'], name='oms_order_broker__e4d41d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['instrument', 'submitted_at'], name='oms_order_instrum_e7e84b_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['execution_id'], name='oms_executi_executi_591d48_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['broker_execution_id'], name='oms_executi_broker__3c1763_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['executed_at'], name='oms_executi_execute_7222b6_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['order', 'executed_at'], name='oms_executi_order_i_435b73_idx'),
        ),
        migrations.AddIndex(
            model_name='pnlsnapshot',
            index=models.Index(fields=['snapshot_date'], name='oms_pnl_sna_snapsho_60e1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pnlsnapshot',
            index=models.Index(fields=['broker_account', 'snapshot_date'], name='oms_pnl_sna_broker__05c112_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pnlsnapshot',
            unique_together={('broker_account', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['broker_account', 'instrument'], name='oms_positio_broker__153e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['quantity'], name='oms_positio_quantit_1ad4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['last_updated'], name='oms_positio_last_up_7a7543_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('broker_account', 'instrument')},
        ),
    ]
