# Generated by Django 5.1.15 on 2026-04-10 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_curve', models.JSONField(default=list)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(choices=[('MEAN_REVERSION', 'Mean Reversion'), ('MOMENTUM', 'Momentum'), ('ARBITRAGE', 'Arbitrage'), ('PAIRS_TRADING', 'Pairs Trading'), ('GRID_TRADING', 'Grid Trading'), ('SCALPING', 'Scalping'), ('SWING_TRADING', 'Swing Trading'), ('OPTIONS_STRATEGY', 'Options Strategy'), ('QUANTITATIVE', 'Quantitative'), ('CUSTOM', 'Custom')], db_index=True, max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('max_position_size', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_daily_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('auto_start', models.BooleanField(default=False)),
                ('paper_trading_only', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
                'db_table': 'strategies_strategy',
                'indexes': [models.Index(fields=['name'], name='strategies__name_d61121_idx'), models.Index(fields=['strategy_type'], name='strategies__strateg_a0511a_idx'), models.Index(fields=['status'], name='strategies__status_612cc0_idx'), models.Index(fields=['is_active'], name='strategies__is_acti_96bc90_idx')],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='SetupPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('setup_type', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=20)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.instrument')),
            ],
            options={
                'db_table': 'strategies_setup_performance',
                'unique_together': {('instrument', 'setup_type', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('daily_trades', models.PositiveIntegerField(default=0)),
                ('daily_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('daily_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('daily_var', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cumulative_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cumulative_trades', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='strategies.strategy')),
            ],
            options={
                'verbose_name': 'strategy performance',
                'verbose_name_plural': 'strategy performances',
                'db_table': 'strategies_strategy_performance',
                'indexes': [models.Index(fields=['date'], name='strategies__date_f298d3_idx'), models.Index(fields=['strategy', 'date'], name='strategies__strateg_7e9a8f_idx')],
                'unique_together': {('strategy', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('winning_trades', models.PositiveIntegerField(default=0)),
                ('losing_trades', models.PositiveIntegerField(default=0)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('parameters_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='strategies.strategy')),
            ],
            options={
                'verbose_name': 'strategy run',
                'verbose_name_plural': 'strategy runs',
                'db_table': 'strategies_strategy_run',
                'indexes': [models.Index(fields=['run_id'], name='strategies__run_id_124a7e_idx'), models.Index(fields=['status'], name='strategies__status_e3c467_idx'), models.Index(fields=['started_at'], name='strategies__started_69521a_idx'), models.Index(fields=['strategy', 'started_at'], name='strategies__strateg_c5e5d2_idx')],
            },
        ),
    ]
