# Generated by Django 5.1.15 on 2026-04-10 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('strategy_name', models.CharField(max_length=100)),
                ('setup_type', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('is_notified', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms.instrument')),
            ],
            options={
                'verbose_name': 'signal log',
                'verbose_name_plural': 'signal logs',
                'db_table': 'strategies_signal_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
