# Generated by Django 6.0.4 on 2026-04-08 22:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oms", "0001_initial"),
        ("strategies", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("setup_type", models.CharField(max_length=100)),
                ("timeframe", models.CharField(max_length=20)),
                ("total_trades", models.PositiveIntegerField(default=0)),
                ("winning_trades", models.PositiveIntegerField(default=0)),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oms.instrument"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_performances",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "strategies_setup_performance",
                "unique_together": {
                    ("tenant", "instrument", "setup_type", "timeframe")
                },
            },
        ),
    ]
