# Generated by Django 5.1.15 on 2026-04-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_signallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='error_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
