# Generated by Django 6.0.4 on 2026-04-09 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oms", "0001_initial"),
        ("strategies", "0002_setupperformance"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("total_trades", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "final_equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("equity_curve", models.JSONField(default=list)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oms.instrument"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
