# Generated by Django 5.1.15 on 2026-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_backtestresult_error_reason_backtestresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='metrics_json',
            field=models.JSONField(default=dict, help_text='Detailed stats: Sharpe, DD, Confluence breakdown'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='rejected_setups',
            field=models.IntegerField(default=0, help_text='Setups filtered by risk or grading'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='total_setups',
            field=models.IntegerField(default=0, help_text='Total ICT/Quant signals detected'),
        ),
    ]
