# Generated by Django 5.1.15 on 2026-04-10 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_backtestresult_metrics_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategies_ml_training_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LearningLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('features_json', models.JSONField(help_text='The snapshot of indicators at the time of signal')),
                ('outcome', models.CharField(help_text='WIN, LOSS, or REJECTED', max_length=20)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('setup_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'strategies_learning_label',
                'indexes': [models.Index(fields=['symbol', 'outcome'], name='strategies__symbol_a64062_idx')],
            },
        ),
    ]
