# Generated by Django 5.1.15 on 2026-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_mltraininglog_learninglabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='signallog',
            name='direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
