# Generated by Django 5.1.15 on 2026-04-10 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('broker_type', models.CharField(choices=[('INTERACTIVE_BROKERS', 'Interactive Brokers'), ('DERIV', 'Deriv'), ('TD_AMERITRADE', 'TD Ameritrade'), ('CHARLES_SCHWAB', 'Charles Schwab'), ('ETRADE', 'E*TRADE'), ('FIDELITY', 'Fidelity'), ('ROBINHOOD', 'Robinhood'), ('ALPACA', 'Alpaca'), ('TRADIER', 'Tradier'), ('CUSTOM', 'Custom')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('use_ssl', models.BooleanField(default=True)),
                ('api_version', models.CharField(blank=True, max_length=20)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_testing', models.BooleanField(db_index=True, default=False)),
                ('website', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('documentation_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'broker',
                'verbose_name_plural': 'brokers',
                'db_table': 'brokers_broker',
                'indexes': [models.Index(fields=['name'], name='brokers_bro_name_b1a8c8_idx'), models.Index(fields=['broker_type'], name='brokers_bro_broker__eac0cb_idx'), models.Index(fields=['is_active'], name='brokers_bro_is_acti_821f17_idx'), models.Index(fields=['is_testing'], name='brokers_bro_is_test_de12dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password_encrypted', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.TextField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('host_override', models.CharField(blank=True, max_length=255)),
                ('port_override', models.PositiveIntegerField(blank=True, null=True)),
                ('use_ssl_override', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DISCONNECTED', 'Disconnected'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='DISCONNECTED', max_length=20)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected', models.DateTimeField(blank=True, null=True)),
                ('connection_errors', models.JSONField(blank=True, default=list)),
                ('trading_hours_start', models.TimeField(blank=True, null=True)),
                ('trading_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_daily_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('auto_reconnect', models.BooleanField(default=True)),
                ('heartbeat_interval', models.PositiveIntegerField(default=30)),
                ('enable_logging', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='brokers.broker')),
            ],
            options={
                'verbose_name': 'broker connection',
                'verbose_name_plural': 'broker connections',
                'db_table': 'brokers_broker_connection',
            },
        ),
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('account_number', models.CharField(db_index=True, max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('JOINT', 'Joint'), ('IRA', 'Individual Retirement Account'), ('401K', '401(k)'), ('TRUST', 'Trust'), ('CORPORATE', 'Corporate'), ('PARTNERSHIP', 'Partnership'), ('LLC', 'Limited Liability Company'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], db_index=True, default='ACTIVE', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('can_trade_stocks', models.BooleanField(default=True)),
                ('can_trade_options', models.BooleanField(default=False)),
                ('can_trade_futures', models.BooleanField(default=False)),
                ('can_trade_forex', models.BooleanField(default=False)),
                ('can_trade_bonds', models.BooleanField(default=False)),
                ('can_trade_mutual_funds', models.BooleanField(default=False)),
                ('risk_tolerance', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive')], default='MODERATE', max_length=20)),
                ('max_leverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('day_trading_buying_power', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('overnight_buying_power', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='brokers.brokerconnection')),
            ],
            options={
                'verbose_name': 'broker account',
                'verbose_name_plural': 'broker accounts',
                'db_table': 'brokers_broker_account',
            },
        ),
        migrations.CreateModel(
            name='BrokerConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_type', models.CharField(choices=[('CONNECT', 'Connect'), ('DISCONNECT', 'Disconnect'), ('RECONNECT', 'Reconnect'), ('ERROR', 'Error'), ('HEARTBEAT', 'Heartbeat'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('API_CALL', 'API Call'), ('ORDER_PLACE', 'Order Place'), ('ORDER_CANCEL', 'Order Cancel'), ('ORDER_MODIFY', 'Order Modify'), ('EXECUTION', 'Execution')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('broker_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='brokers.brokerconnection')),
            ],
            options={
                'verbose_name': 'broker connection log',
                'verbose_name_plural': 'broker connection logs',
                'db_table': 'brokers_broker_connection_log',
            },
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['broker'], name='brokers_bro_broker__74348c_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['status'], name='brokers_bro_status_03bd94_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['status', 'last_connected'], name='brokers_bro_status_ccd30d_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnection',
            index=models.Index(fields=['broker', 'status'], name='brokers_bro_broker__e3bb89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokerconnection',
            unique_together={('broker', 'name')},
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['broker_connection'], name='brokers_bro_broker__2f21d4_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['status'], name='brokers_bro_status_9ad96e_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['account_number'], name='brokers_bro_account_9aad29_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['status', 'can_trade_stocks'], name='brokers_bro_status_36b79a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokeraccount',
            unique_together={('broker_connection', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='brokerconnectionlog',
            index=models.Index(fields=['broker_connection'], name='brokers_bro_broker__12f716_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnectionlog',
            index=models.Index(fields=['event_type'], name='brokers_bro_event_t_c462a7_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnectionlog',
            index=models.Index(fields=['event_type', 'created_at'], name='brokers_bro_event_t_e3ebc1_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconnectionlog',
            index=models.Index(fields=['level', 'created_at'], name='brokers_bro_level_594a34_idx'),
        ),
    ]
