# Generated by Django 6.0.4 on 2026-04-08 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brokers", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccount",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_accounts",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="brokerconnection",
            name="broker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="brokers.broker",
            ),
        ),
        migrations.AddField(
            model_name="brokerconnection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_connections",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="broker_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="brokers.brokerconnection",
            ),
        ),
        migrations.AddField(
            model_name="brokerconnectionlog",
            name="broker_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_logs",
                to="brokers.brokerconnection",
            ),
        ),
        migrations.AddField(
            model_name="brokerconnectionlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_connection_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnection",
            index=models.Index(
                fields=["tenant", "broker"], name="brokers_bro_tenant__e6794a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnection",
            index=models.Index(
                fields=["tenant", "status"], name="brokers_bro_tenant__e9e597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnection",
            index=models.Index(
                fields=["status", "last_connected"],
                name="brokers_bro_status_ccd30d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnection",
            index=models.Index(
                fields=["broker", "status"], name="brokers_bro_broker__e3bb89_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brokerconnection",
            unique_together={("tenant", "broker", "name")},
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["tenant", "broker_connection"],
                name="brokers_bro_tenant__0b5085_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["tenant", "status"], name="brokers_bro_tenant__f96b70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["account_number"], name="brokers_bro_account_9aad29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["status", "can_trade_stocks"],
                name="brokers_bro_status_36b79a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brokeraccount",
            unique_together={("tenant", "broker_connection", "account_number")},
        ),
        migrations.AddIndex(
            model_name="brokerconnectionlog",
            index=models.Index(
                fields=["tenant", "broker_connection"],
                name="brokers_bro_tenant__935450_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnectionlog",
            index=models.Index(
                fields=["tenant", "event_type"], name="brokers_bro_tenant__950552_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnectionlog",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="brokers_bro_event_t_e3ebc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerconnectionlog",
            index=models.Index(
                fields=["level", "created_at"], name="brokers_bro_level_594a34_idx"
            ),
        ),
    ]
