# Generated by Django 6.0.4 on 2026-04-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broker",
            name="broker_type",
            field=models.CharField(
                choices=[
                    ("INTERACTIVE_BROKERS", "Interactive Brokers"),
                    ("DERIV", "Deriv"),
                    ("TD_AMERITRADE", "TD Ameritrade"),
                    ("CHARLES_SCHWAB", "Charles Schwab"),
                    ("ETRADE", "E*TRADE"),
                    ("FIDELITY", "Fidelity"),
                    ("ROBINHOOD", "Robinhood"),
                    ("ALPACA", "Alpaca"),
                    ("TRADIER", "Tradier"),
                    ("CUSTOM", "Custom"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
