<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-08 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
=======
# Generated by Django 5.1.15 on 2026-04-10 20:49

import uuid
>>>>>>> origin/main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("oms", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/main
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="MarketSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("REALTIME", "Real-time"),
                            ("SNAPSHOT", "Snapshot"),
                            ("HISTORICAL", "Historical"),
                            ("OPTION_CHAIN", "Option Chain"),
                            ("LEVEL_1", "Level 1"),
                            ("LEVEL_2", "Level 2"),
                            ("NEWS", "News"),
                            ("FUNDAMENTALS", "Fundamentals"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("CANCELLED", "Cancelled"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("fields", models.JSONField(blank=True, default=list)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "max_ticks_per_second",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_ticks_per_minute",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_data_received", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_subscriptions",
                        to="oms.instrument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_subscriptions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "market subscription",
                "verbose_name_plural": "market subscriptions",
                "db_table": "marketdata_market_subscription",
            },
        ),
        migrations.CreateModel(
            name="MarketDataStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "stream_type",
                    models.CharField(
                        choices=[
                            ("WEBSOCKET", "WebSocket"),
                            ("SERVER_SENT_EVENTS", "Server-Sent Events"),
                            ("POLLING", "Polling"),
                            ("GRPC", "gRPC"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "connection_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_data_sent", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data_streams",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriptions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="data_streams",
                        to="marketdata.marketsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "market data stream",
                "verbose_name_plural": "market data streams",
                "db_table": "marketdata_market_data_stream",
            },
        ),
        migrations.CreateModel(
            name="TickData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tick_type",
                    models.CharField(
                        choices=[
                            ("BID", "Bid"),
                            ("ASK", "Ask"),
                            ("TRADE", "Trade"),
                            ("BID_SIZE", "Bid Size"),
                            ("ASK_SIZE", "Ask Size"),
                            ("LAST_SIZE", "Last Size"),
                            ("HIGH", "High"),
                            ("LOW", "Low"),
                            ("OPEN", "Open"),
                            ("CLOSE", "Close"),
                            ("VOLUME", "Volume"),
                            ("OPTION_IMPLIED_VOLATILITY", "Option Implied Volatility"),
                            ("OPTION_VOLUME", "Option Volume"),
                            ("OPTION_OPEN_INTEREST", "Option Open Interest"),
                            ("OPTION_DELTA", "Option Delta"),
                            ("OPTION_GAMMA", "Option Gamma"),
                            ("OPTION_THETA", "Option Theta"),
                            ("OPTION_VEGA", "Option Vega"),
                            ("FUTURE_BASIS", "Future Basis"),
                            ("FUTURE_OPEN_INTEREST", "Future Open Interest"),
                            ("NEWS", "News"),
                            ("FUNDAMENTAL", "Fundamental"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("tick_time", models.DateTimeField(db_index=True)),
                ("exchange", models.CharField(blank=True, max_length=20)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tick_data",
                        to="oms.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "tick data",
                "verbose_name_plural": "tick data",
                "db_table": "marketdata_tick_data",
            },
        ),
        migrations.CreateModel(
            name="HistoricalData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("OHLC", "OHLC"),
                            ("TRADE", "Trade"),
                            ("BID_ASK", "Bid/Ask"),
                            ("VOLUME", "Volume"),
                            ("GREEKS", "Option Greeks"),
                            ("IMPLIED_VOLATILITY", "Implied Volatility"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("1_MINUTE", "1 Minute"),
                            ("5_MINUTE", "5 Minutes"),
                            ("15_MINUTE", "15 Minutes"),
                            ("30_MINUTE", "30 Minutes"),
                            ("1_HOUR", "1 Hour"),
                            ("4_HOUR", "4 Hours"),
                            ("1_DAY", "1 Day"),
                            ("1_WEEK", "1 Week"),
                            ("1_MONTH", "1 Month"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("open_interest", models.BigIntegerField(blank=True, null=True)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_data",
                        to="oms.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical data",
                "verbose_name_plural": "historical data",
                "db_table": "marketdata_historical_data",
                "indexes": [
                    models.Index(
                        fields=["data_type"], name="marketdata__data_ty_987b72_idx"
                    ),
                    models.Index(
                        fields=["interval"], name="marketdata__interva_9be8ad_idx"
                    ),
                    models.Index(
                        fields=["start_time"], name="marketdata__start_t_630241_idx"
                    ),
                    models.Index(
                        fields=["end_time"], name="marketdata__end_tim_3a995a_idx"
                    ),
                    models.Index(
                        fields=["instrument", "data_type", "interval", "start_time"],
                        name="marketdata__instrum_c94f36_idx",
                    ),
                ],
                "unique_together": {
                    ("instrument", "data_type", "interval", "start_time")
                },
            },
        ),
        migrations.CreateModel(
            name="MarketDataCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("LAST_PRICE", "Last Price"),
                            ("BID_ASK", "Bid/Ask"),
                            ("OHLC", "OHLC"),
                            ("VOLUME", "Volume"),
                            ("GREEKS", "Option Greeks"),
                            ("IMPLIED_VOLATILITY", "Implied Volatility"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("cache_key", models.CharField(db_index=True, max_length=200)),
                ("cached_data", models.JSONField(blank=True, default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data_cache",
                        to="oms.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "market data cache",
                "verbose_name_plural": "market data cache",
                "db_table": "marketdata_market_data_cache",
                "indexes": [
                    models.Index(
                        fields=["cache_type"], name="marketdata__cache_t_a4b338_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="marketdata__last_up_714b0c_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="marketdata__expires_d9924c_idx"
                    ),
                    models.Index(
                        fields=["instrument", "cache_type"],
                        name="marketdata__instrum_2e59da_idx",
                    ),
                ],
                "unique_together": {("instrument", "cache_type", "cache_key")},
            },
        ),
        migrations.AddIndex(
            model_name="marketsubscription",
            index=models.Index(
                fields=["subscription_type"], name="marketdata__subscri_387e51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubscription",
            index=models.Index(fields=["status"], name="marketdata__status_ace366_idx"),
        ),
        migrations.AddIndex(
            model_name="marketsubscription",
            index=models.Index(
                fields=["is_active"], name="marketdata__is_acti_12bf48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubscription",
            index=models.Index(
                fields=["last_data_received"], name="marketdata__last_da_923178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketsubscription",
            index=models.Index(
                fields=["user", "created_at"], name="marketdata__user_id_291220_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketsubscription",
            unique_together={("tenant", "instrument", "subscription_type")},
        ),
        migrations.AddIndex(
            model_name="marketdatastream",
            index=models.Index(fields=["name"], name="marketdata__name_93f61b_idx"),
        ),
        migrations.AddIndex(
            model_name="marketdatastream",
            index=models.Index(
                fields=["stream_type"], name="marketdata__stream__d9bcc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketdatastream",
            index=models.Index(fields=["status"], name="marketdata__status_a36002_idx"),
        ),
        migrations.AddIndex(
            model_name="marketdatastream",
            index=models.Index(
                fields=["is_active"], name="marketdata__is_acti_66ec55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketdatastream",
            index=models.Index(
                fields=["connection_id"], name="marketdata__connect_0837ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketdatastream",
            index=models.Index(
                fields=["user", "created_at"], name="marketdata__user_id_74b904_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketdatastream",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(
                fields=["tick_type"], name="marketdata__tick_ty_09ab96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(
                fields=["tick_time"], name="marketdata__tick_ti_9603e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(
                fields=["instrument", "tick_time"],
                name="marketdata__instrum_6b7ff8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tickdata",
            index=models.Index(
                fields=["instrument", "tick_type", "tick_time"],
                name="marketdata__instrum_a311b1_idx",
            ),
        ),
=======
            name='HistoricalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('data_type', models.CharField(choices=[('OHLC', 'OHLC'), ('TRADE', 'Trade'), ('BID_ASK', 'Bid/Ask'), ('VOLUME', 'Volume'), ('GREEKS', 'Option Greeks'), ('IMPLIED_VOLATILITY', 'Implied Volatility')], db_index=True, max_length=20)),
                ('interval', models.CharField(choices=[('1_MINUTE', '1 Minute'), ('5_MINUTE', '5 Minutes'), ('15_MINUTE', '15 Minutes'), ('30_MINUTE', '30 Minutes'), ('1_HOUR', '1 Hour'), ('4_HOUR', '4 Hours'), ('1_DAY', '1 Day'), ('1_WEEK', '1 Week'), ('1_MONTH', '1 Month')], db_index=True, max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'historical data',
                'verbose_name_plural': 'historical data',
                'db_table': 'marketdata_historical_data',
            },
        ),
        migrations.CreateModel(
            name='MarketDataCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cache_type', models.CharField(choices=[('LAST_PRICE', 'Last Price'), ('BID_ASK', 'Bid/Ask'), ('OHLC', 'OHLC'), ('VOLUME', 'Volume'), ('GREEKS', 'Option Greeks'), ('IMPLIED_VOLATILITY', 'Implied Volatility')], db_index=True, max_length=30)),
                ('cache_key', models.CharField(db_index=True, max_length=200)),
                ('cached_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'market data cache',
                'verbose_name_plural': 'market data cache',
                'db_table': 'marketdata_market_data_cache',
            },
        ),
        migrations.CreateModel(
            name='MarketDataStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('stream_type', models.CharField(choices=[('WEBSOCKET', 'WebSocket'), ('SERVER_SENT_EVENTS', 'Server-Sent Events'), ('POLLING', 'Polling'), ('GRPC', 'gRPC')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('connection_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_data_sent', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'market data stream',
                'verbose_name_plural': 'market data streams',
                'db_table': 'marketdata_market_data_stream',
            },
        ),
        migrations.CreateModel(
            name='MarketSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('subscription_type', models.CharField(choices=[('REALTIME', 'Real-time'), ('SNAPSHOT', 'Snapshot'), ('HISTORICAL', 'Historical'), ('OPTION_CHAIN', 'Option Chain'), ('LEVEL_1', 'Level 1'), ('LEVEL_2', 'Level 2'), ('NEWS', 'News'), ('FUNDAMENTALS', 'Fundamentals')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_ticks_per_second', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ticks_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_data_received', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'market subscription',
                'verbose_name_plural': 'market subscriptions',
                'db_table': 'marketdata_market_subscription',
            },
        ),
        migrations.CreateModel(
            name='TickData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tick_type', models.CharField(choices=[('BID', 'Bid'), ('ASK', 'Ask'), ('TRADE', 'Trade'), ('BID_SIZE', 'Bid Size'), ('ASK_SIZE', 'Ask Size'), ('LAST_SIZE', 'Last Size'), ('HIGH', 'High'), ('LOW', 'Low'), ('OPEN', 'Open'), ('CLOSE', 'Close'), ('VOLUME', 'Volume'), ('OPTION_IMPLIED_VOLATILITY', 'Option Implied Volatility'), ('OPTION_VOLUME', 'Option Volume'), ('OPTION_OPEN_INTEREST', 'Option Open Interest'), ('OPTION_DELTA', 'Option Delta'), ('OPTION_GAMMA', 'Option Gamma'), ('OPTION_THETA', 'Option Theta'), ('OPTION_VEGA', 'Option Vega'), ('FUTURE_BASIS', 'Future Basis'), ('FUTURE_OPEN_INTEREST', 'Future Open Interest'), ('NEWS', 'News'), ('FUNDAMENTAL', 'Fundamental')], db_index=True, max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('tick_time', models.DateTimeField(db_index=True)),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'tick data',
                'verbose_name_plural': 'tick data',
                'db_table': 'marketdata_tick_data',
            },
        ),
>>>>>>> origin/main
    ]
