# Generated by Django 5.1.15 on 2026-04-10 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('data_type', models.CharField(choices=[('OHLC', 'OHLC'), ('TRADE', 'Trade'), ('BID_ASK', 'Bid/Ask'), ('VOLUME', 'Volume'), ('GREEKS', 'Option Greeks'), ('IMPLIED_VOLATILITY', 'Implied Volatility')], db_index=True, max_length=20)),
                ('interval', models.CharField(choices=[('1_MINUTE', '1 Minute'), ('5_MINUTE', '5 Minutes'), ('15_MINUTE', '15 Minutes'), ('30_MINUTE', '30 Minutes'), ('1_HOUR', '1 Hour'), ('4_HOUR', '4 Hours'), ('1_DAY', '1 Day'), ('1_WEEK', '1 Week'), ('1_MONTH', '1 Month')], db_index=True, max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'historical data',
                'verbose_name_plural': 'historical data',
                'db_table': 'marketdata_historical_data',
            },
        ),
        migrations.CreateModel(
            name='MarketDataCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cache_type', models.CharField(choices=[('LAST_PRICE', 'Last Price'), ('BID_ASK', 'Bid/Ask'), ('OHLC', 'OHLC'), ('VOLUME', 'Volume'), ('GREEKS', 'Option Greeks'), ('IMPLIED_VOLATILITY', 'Implied Volatility')], db_index=True, max_length=30)),
                ('cache_key', models.CharField(db_index=True, max_length=200)),
                ('cached_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'market data cache',
                'verbose_name_plural': 'market data cache',
                'db_table': 'marketdata_market_data_cache',
            },
        ),
        migrations.CreateModel(
            name='MarketDataStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('stream_type', models.CharField(choices=[('WEBSOCKET', 'WebSocket'), ('SERVER_SENT_EVENTS', 'Server-Sent Events'), ('POLLING', 'Polling'), ('GRPC', 'gRPC')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('connection_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_data_sent', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'market data stream',
                'verbose_name_plural': 'market data streams',
                'db_table': 'marketdata_market_data_stream',
            },
        ),
        migrations.CreateModel(
            name='MarketSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('subscription_type', models.CharField(choices=[('REALTIME', 'Real-time'), ('SNAPSHOT', 'Snapshot'), ('HISTORICAL', 'Historical'), ('OPTION_CHAIN', 'Option Chain'), ('LEVEL_1', 'Level 1'), ('LEVEL_2', 'Level 2'), ('NEWS', 'News'), ('FUNDAMENTALS', 'Fundamentals')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], db_index=True, default='ACTIVE', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_ticks_per_second', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ticks_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_data_received', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'market subscription',
                'verbose_name_plural': 'market subscriptions',
                'db_table': 'marketdata_market_subscription',
            },
        ),
        migrations.CreateModel(
            name='TickData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tick_type', models.CharField(choices=[('BID', 'Bid'), ('ASK', 'Ask'), ('TRADE', 'Trade'), ('BID_SIZE', 'Bid Size'), ('ASK_SIZE', 'Ask Size'), ('LAST_SIZE', 'Last Size'), ('HIGH', 'High'), ('LOW', 'Low'), ('OPEN', 'Open'), ('CLOSE', 'Close'), ('VOLUME', 'Volume'), ('OPTION_IMPLIED_VOLATILITY', 'Option Implied Volatility'), ('OPTION_VOLUME', 'Option Volume'), ('OPTION_OPEN_INTEREST', 'Option Open Interest'), ('OPTION_DELTA', 'Option Delta'), ('OPTION_GAMMA', 'Option Gamma'), ('OPTION_THETA', 'Option Theta'), ('OPTION_VEGA', 'Option Vega'), ('FUTURE_BASIS', 'Future Basis'), ('FUTURE_OPEN_INTEREST', 'Future Open Interest'), ('NEWS', 'News'), ('FUNDAMENTAL', 'Fundamental')], db_index=True, max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('tick_time', models.DateTimeField(db_index=True)),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'tick data',
                'verbose_name_plural': 'tick data',
                'db_table': 'marketdata_tick_data',
            },
        ),
    ]
