# Generated by Django 5.1.15 on 2026-04-10 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketdata', '0001_initial'),
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='oms.instrument'),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_cache', to='oms.instrument'),
        ),
        migrations.AddField(
            model_name='marketsubscription',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_subscriptions', to='oms.instrument'),
        ),
        migrations.AddField(
            model_name='marketdatastream',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='data_streams', to='marketdata.marketsubscription'),
        ),
        migrations.AddField(
            model_name='tickdata',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data', to='oms.instrument'),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['data_type'], name='marketdata__data_ty_987b72_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['interval'], name='marketdata__interva_9be8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['start_time'], name='marketdata__start_t_630241_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['end_time'], name='marketdata__end_tim_3a995a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaldata',
            index=models.Index(fields=['instrument', 'data_type', 'interval', 'start_time'], name='marketdata__instrum_c94f36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicaldata',
            unique_together={('instrument', 'data_type', 'interval', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='marketdatacache',
            index=models.Index(fields=['cache_type'], name='marketdata__cache_t_a4b338_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatacache',
            index=models.Index(fields=['last_updated'], name='marketdata__last_up_714b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatacache',
            index=models.Index(fields=['expires_at'], name='marketdata__expires_d9924c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatacache',
            index=models.Index(fields=['instrument', 'cache_type'], name='marketdata__instrum_2e59da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketdatacache',
            unique_together={('instrument', 'cache_type', 'cache_key')},
        ),
        migrations.AddIndex(
            model_name='marketsubscription',
            index=models.Index(fields=['subscription_type'], name='marketdata__subscri_387e51_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsubscription',
            index=models.Index(fields=['status'], name='marketdata__status_ace366_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsubscription',
            index=models.Index(fields=['is_active'], name='marketdata__is_acti_12bf48_idx'),
        ),
        migrations.AddIndex(
            model_name='marketsubscription',
            index=models.Index(fields=['last_data_received'], name='marketdata__last_da_923178_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketsubscription',
            unique_together={('instrument', 'subscription_type')},
        ),
        migrations.AddIndex(
            model_name='marketdatastream',
            index=models.Index(fields=['name'], name='marketdata__name_93f61b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatastream',
            index=models.Index(fields=['stream_type'], name='marketdata__stream__d9bcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatastream',
            index=models.Index(fields=['status'], name='marketdata__status_a36002_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatastream',
            index=models.Index(fields=['is_active'], name='marketdata__is_acti_66ec55_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatastream',
            index=models.Index(fields=['connection_id'], name='marketdata__connect_0837ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketdatastream',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='tickdata',
            index=models.Index(fields=['tick_type'], name='marketdata__tick_ty_09ab96_idx'),
        ),
        migrations.AddIndex(
            model_name='tickdata',
            index=models.Index(fields=['tick_time'], name='marketdata__tick_ti_9603e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tickdata',
            index=models.Index(fields=['instrument', 'tick_time'], name='marketdata__instrum_6b7ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='tickdata',
            index=models.Index(fields=['instrument', 'tick_type', 'tick_time'], name='marketdata__instrum_a311b1_idx'),
        ),
    ]
